"""Replay every stored hold phrase through the arbiter and count what changes.

    python -m scripts.replay_hold_speech            # whole corpus
    python -m scripts.replay_hold_speech --clinic vital_edge

Prosody cannot be proved offline — the joined seam and the open-clause contour
are audible-only and need the demo line. Everything else can: whether a phrase
would be spoken at all, whether it would stack, and whether it would describe
work that was not happening. Those are the three defects that made up almost all
of the 354 hold phrases in the obs corpus, and they are decided by decide_hold,
which is pure.

Reads OBS_DATABASE_URL (falls back to DATABASE_URL), the same as scripts/show_call.py.

WHAT THE CLASSIFIER CAN AND CANNOT SEE
--------------------------------------
obs stores what was SAID, not what the engine did: there is no tool trace, so
"was a tool in flight?" is inferred from what Susie said next. A phrase followed
by a question and no data is counted as a turn where no lookup happened. That is
the same inference the defect count was built on, and it is conservative in the
direction that matters — a turn miscounted as "had work" makes the new system
look no better, never better than it is.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.hold_speech import WorkKind, decide_hold  # noqa: E402

# The deterministic phrases as they were shipped, lower-cased. Anything matching
# one of these exactly was spoken by the engine, not generated by the model.
LEGACY_HEADS = {p.lower() for p in [
    "Let me have a look at what we've got…", "One moment while I check that for you…",
    "Just checking the diary now…", "I'll take a look at the schedule for you…",
    "Let me pull that up now…", "Checking what's free for you…",
    "Let me see what we have available…", "Nearly there…", "Won't be long now…",
    "Almost got it…", "No problem at all — let me find that for you…",
    "Of course — just pulling your appointment up…", "Let me bring that up for you…",
    "One moment while I find that for you…", "Let me take a look for you…",
    "Just getting that into the diary for you…", "Just locking that in now…",
    "Popping that in the diary…", "No problem at all — I'm taking care of that for you now…",
    "That's absolutely fine — sorting that for you now…", "Not to worry — doing that for you now…",
    "No problem at all — I'm moving that for you now…", "Of course — getting that changed for you now…",
    "That's fine — shifting that across for you now…", "Just getting that for you…",
    "Right with you…", "One moment…", "Let me just check that…",
    "Just moving that for you now…", "Let me get that sorted for you.",
]}

# Data the caller was actually waiting for. A phrase followed by one of these
# stood in front of real work; a phrase followed by none of them did not.
_HAS_DATA = re.compile(
    r"\bnumber\s+\d|\b\d{1,2}(st|nd|rd|th)\b|\bavailable\b|\bearliest\b|"
    r"\bi can see\b|\bthat's (all )?(done|cancelled|booked)\b|\bi'm afraid\b|"
    r"\bhaven't got\b|\bnot finding\b|\bsent it to\b|\bsubject to\b",
    re.IGNORECASE,
)


def _load(clinic: str | None):
    from sqlalchemy import create_engine, text
    url = os.getenv("OBS_DATABASE_URL") or os.getenv("DATABASE_URL")
    if not url:
        raise SystemExit("OBS_DATABASE_URL is not set")
    q = "select call_sid, clinic_id, transcript from calls where transcript is not null"
    if clinic:
        q += " and clinic_id = :c"
    eng = create_engine(url)
    with eng.connect() as conn:
        rows = conn.execute(text(q), {"c": clinic} if clinic else {}).fetchall()
    out = []
    for sid, cid, tr in rows:
        if isinstance(tr, str):
            tr = json.loads(tr)
        if tr:
            out.append((sid, cid, tr))
    return out


def replay(calls) -> Counter:
    c = Counter()
    for _sid, _cid, tr in calls:
        for i, turn in enumerate(tr):
            if turn.get("role") != "assistant":
                continue
            text_ = (turn.get("text") or "").strip()
            if text_.lower() not in LEGACY_HEADS:
                continue
            c["legacy_heads"] += 1

            # Everything Susie said after this, up to the caller's next turn.
            after, stacked = None, 0
            for j in range(i + 1, len(tr)):
                if tr[j].get("role") == "user":
                    break
                nxt = (tr[j].get("text") or "").strip()
                if nxt.lower() in LEGACY_HEADS:
                    stacked += 1
                    continue
                after = nxt
                break

            if stacked:
                c["legacy_stacked"] += 1
            if after is None:
                c["legacy_dead_end"] += 1
                work = WorkKind.NONE
            elif _HAS_DATA.search(after):
                work = WorkKind.DIARY_READ          # real work stood behind it
            else:
                c["legacy_promised_nothing"] += 1
                work = WorkKind.NONE                # a question, not data

            # The arbiter's verdict. head_already_spoken=False because each of
            # these is evaluated as the FIRST head of its turn; the stacked ones
            # are counted separately below.
            d = decide_hold(kind=work, head_already_spoken=False)
            if d.speak:
                c["new_speaks"] += 1
            else:
                c["new_silent"] += 1
            # A stacked follower always loses the latch, by construction.
            c["new_stacked"] += 0
    return c


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--clinic")
    args = ap.parse_args()

    try:
        from dotenv import load_dotenv
        load_dotenv(".env")
    except Exception:
        pass

    calls = _load(args.clinic)
    c = replay(calls)

    print(f"calls replayed                     : {len(calls)}")
    print(f"hold phrases the engine spoke      : {c['legacy_heads']}")
    print()
    print("BEFORE")
    print(f"  promised work that never happened: {c['legacy_promised_nothing']}")
    print(f"  dead ends (nothing followed)     : {c['legacy_dead_end']}")
    print(f"  stacked behind another phrase    : {c['legacy_stacked']}")
    print()
    print("AFTER (same turns, through decide_hold)")
    print(f"  spoken                           : {c['new_speaks']}")
    print(f"  silent                           : {c['new_silent']}")
    print(f"  stacked                          : {c['new_stacked']}"
          "   (one head per turn is structural)")


if __name__ == "__main__":
    main()
