"""Replay every stored caller turn through the situational head and report.

    python -m scripts.replay_situational_heads                 # the numbers
    python -m scripts.replay_situational_heads --sentences 40  # + the sentences
    python -m scripts.replay_situational_heads --clinic vital_edge

WHY THIS EXISTS
---------------
The hold-speech question cannot be settled by ear. The evidence base is a
DISTRIBUTION -- 601 engine-spoken hold phrases across 172 of 733 stored calls,
one call with 17 -- and on any single well-behaved call the difference is one
phrase, inaudible by design. A corpus-level change needs a corpus-level
measurement.

Everything that matters here is decidable offline, because `classify_intent`,
`subject_for`, `render_intent_head`, `strip_head_echo` and `join_after_head` are
all pure. Prosody is the exception and stays a listening job: whether the joined
seam actually sounds like one sentence needs the demo line.

WHAT THE CLASSIFIER CAN AND CANNOT SEE
--------------------------------------
obs stores what was SAID, not what the engine did: there is no tool trace. The
session flags the live path reads -- `pending_screen` above all -- are not in
the transcript either, so this replay sees only the WEAKER of the two screening
guards. That biases every number here against the new behaviour: some turns
counted as "head spoken" would be silent live. Conservative in the direction
that matters, which is the same choice scripts/replay_hold_speech.py made.

Reads OBS_DATABASE_URL (falls back to DATABASE_URL).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.hold_speech import _NAMES_THE_WORK  # noqa: E402
from app.hold_speech import (  # noqa: E402
    classify_intent,
    render_intent_head,
    strip_head_echo,
    subject_for,
)
from app.media_streams.llm_stream import join_after_head  # noqa: E402

#: The deterministic phrases as shipped, lower-cased. Anything matching one of
#: these exactly was spoken by the ENGINE, not generated by the model -- which
#: is what makes "how many hold phrases did this call contain?" answerable.
LEGACY_HEADS = {p.lower() for p in [
    "Let me have a look at what we've got…", "One moment while I check that for you…",
    "Just checking the diary now…", "I'll take a look at the schedule for you…",
    "Let me pull that up now…", "Checking what's free for you…",
    "Let me see what we have available…", "Nearly there…", "Won't be long now…",
    "Almost got it…", "No problem at all — let me find that for you…",
    "Of course — just pulling your appointment up…", "Let me bring that up for you…",
    "One moment while I find that for you…", "Let me take a look for you…",
    "Just getting that into the diary for you…", "Just locking that in now…",
    "Popping that in the diary…", "No problem at all — I'm taking care of that for you now…",
    "That's absolutely fine — sorting that for you now…", "Not to worry — doing that for you now…",
    "No problem at all — I'm moving that for you now…", "Of course — getting that changed for you now…",
    "That's fine — shifting that across for you now…", "Just getting that for you…",
    "Right with you…", "One moment…", "Let me just check that…",
    "Just moving that for you now…", "Let me get that sorted for you.",
]}


def load(clinic=None):
    from sqlalchemy import create_engine, text

    url = os.getenv("OBS_DATABASE_URL") or os.getenv("DATABASE_URL")
    if not url:
        raise SystemExit("OBS_DATABASE_URL is not set")
    query = ("select call_sid, clinic_id, transcript from calls "
             "where transcript is not null")
    if clinic:
        query += " and clinic_id = :c"
    engine = create_engine(url)
    with engine.connect() as conn:
        rows = conn.execute(text(query), {"c": clinic} if clinic else {}).fetchall()
    out = []
    for sid, cid, transcript in rows:
        if isinstance(transcript, str):
            transcript = json.loads(transcript)
        if transcript:
            out.append((sid, cid, transcript))
    return out


def _prev_assistant(transcript, i):
    for j in range(i - 1, -1, -1):
        if transcript[j].get("role") == "assistant":
            return transcript[j].get("text") or ""
    return ""


def _payload(transcript, i):
    """Susie's next substantive turn, up to the caller's next one.

    Stopping at the caller matters: anything past that is a reply to a
    different question, and counting it would make a dead end look answered.
    """
    for j in range(i + 1, len(transcript)):
        if transcript[j].get("role") == "user":
            return ""
        if transcript[j].get("role") != "assistant":
            continue
        text = (transcript[j].get("text") or "").strip()
        if text.lower() in LEGACY_HEADS:
            continue
        if len(text) > 25:
            return text
    return ""


def replay(calls, sample_size=0):
    counts = Counter()
    by_intent = Counter()
    before_per_call = Counter()
    after_per_call = Counter()
    samples = []

    for _sid, _cid, transcript in calls:
        before = sum(
            1 for t in transcript
            if t.get("role") == "assistant"
            and (t.get("text") or "").strip().lower() in LEGACY_HEADS
        )
        before_per_call[before] += 1
        counts["legacy_heads"] += before
        for i, turn in enumerate(transcript):
            if turn.get("role") != "assistant":
                continue
            if (turn.get("text") or "").strip().lower() not in LEGACY_HEADS:
                continue
            if _NAMES_THE_WORK.search(turn.get("text") or ""):
                counts["legacy_claims_work"] += 1
            if not _payload(transcript, i):
                counts["legacy_dead_end"] += 1

        after = 0
        for i, turn in enumerate(transcript):
            if turn.get("role") != "user":
                continue
            utterance = (turn.get("text") or "").strip()
            if not utterance:
                continue
            counts["caller_turns"] += 1

            hits = classify_intent(utterance, _prev_assistant(transcript, i))
            if not hits:
                counts["silent"] += 1
                continue
            intent = hits[0]
            head = render_intent_head(intent, subject=subject_for(utterance))
            if not head:
                counts["silent"] += 1
                continue

            after += 1
            counts["heads"] += 1
            if _NAMES_THE_WORK.search(head):
                counts["claims_work"] += 1
            by_intent[intent.value] += 1

            payload = _payload(transcript, i)
            if not payload:
                # A head with nothing behind it is the dead-end defect. 42 of
                # the stored legacy phrases were exactly this.
                counts["dead_end"] += 1
                continue
            stripped = strip_head_echo(payload, head)
            if stripped != payload:
                counts["opener_stripped"] += 1
            joined = f"{head} {join_after_head(stripped, head)}"
            if len(samples) < sample_size:
                samples.append((intent.value, utterance, payload, joined))
        after_per_call[after] += 1

    return counts, by_intent, before_per_call, after_per_call, samples


def _pct(n, total):
    return f"{100.0 * n / total:.1f}%" if total else "n/a"


def _dist(counter, top=8):
    total_calls = sum(counter.values())
    total_heads = sum(k * v for k, v in counter.items())
    worst = max(counter) if counter else 0
    with_any = sum(v for k, v in counter.items() if k)
    return total_calls, total_heads, with_any, worst


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clinic")
    parser.add_argument("--sentences", type=int, default=0,
                        help="print N joined before/after sentences")
    args = parser.parse_args()

    try:
        from dotenv import load_dotenv
        load_dotenv(".env")
    except Exception:
        pass

    calls = load(args.clinic)
    counts, by_intent, before_pc, after_pc, samples = replay(calls, args.sentences)

    n_calls, before_total, before_any, before_worst = _dist(before_pc)
    _, after_total, after_any, after_worst = _dist(after_pc)

    print(f"calls replayed                     : {n_calls}")
    print(f"caller turns                       : {counts['caller_turns']}")
    print()
    print("BEFORE -- deterministic hold phrases the engine spoke")
    print(f"  total                            : {before_total}")
    print(f"  calls containing at least one    : {before_any}")
    print(f"  worst single call                : {before_worst}")
    print(f"  that CLAIM a lookup or a write   : {counts['legacy_claims_work']}"
          f"  ({_pct(counts['legacy_claims_work'], before_total)})")
    print(f"  DEAD ENDS (nothing followed)     : {counts['legacy_dead_end']}"
          f"  ({_pct(counts['legacy_dead_end'], before_total)})")
    print()
    print("AFTER -- situational heads")
    print(f"  total                            : {after_total}")
    print(f"  calls containing at least one    : {after_any}")
    print(f"  worst single call                : {after_worst}")
    print("  NOTE: the totals are not comparable. A legacy phrase was an extra")
    print("        UTTERANCE; a head is the opening clause of the reply itself,")
    print("        so more of them is not more talking. The rates below are the")
    print("        like-for-like comparison, and the dead-end rate is the one")
    print("        that matters: a head with nothing behind it is the defect.")
    print(f"  turns left silent (unchanged)    : {counts['silent']}")
    print(f"  model's duplicate opener removed : {counts['opener_stripped']}")
    print(f"  that CLAIM a lookup or a write   : {counts['claims_work']}"
          f"  ({_pct(counts['claims_work'], after_total)})")
    print(f"  DEAD ENDS (nothing followed)     : {counts['dead_end']}"
          f"  ({_pct(counts['dead_end'], after_total)})")
    print()
    print("situations covered")
    for intent, n in by_intent.most_common():
        print(f"  {n:5d}  {intent}")

    if samples:
        print()
        print("=" * 78)
        for intent, caller, payload, joined in samples:
            print(f"\n[{intent}]")
            print(f"  caller : {caller[:100]}")
            print(f"  before : {payload[:110]}")
            print(f"  after  : {joined[:150]}")


if __name__ == "__main__":
    main()
