"""
Regression: the hold clip must not be the same recording every time.

Owner report, 2026-08-08 — "latency is great but it sounds quite robotic".
`FillerGuard` held ONE `bytes` per slot and replayed it, so every availability
lookup in every call played a byte-identical waveform. Identical words can pass
unnoticed in a real conversation; an identical *recording* cannot, and the tell
is the second playing.

Two properties are worth pinning, and neither can be checked by ear on a live
call without placing several of them:

  1. the pool is discovered as a contiguous ascending sequence, so a stray file
     in audio_clips/ can never be played to a patient, and
  2. the same variant never plays twice in a row on one call.

Both are exercised against pure functions and against a real armed guard, with
clips written to tmp_path — this test must not depend on the committed audio,
which is generated by hand with a paid key and may be a pool of one on a branch
that has not regenerated yet.
"""
from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from app.media_streams.filler_guard import (
    FillerGuard,
    discover_clip_pool,
    next_clip_index,
)


# ── 1. Pool discovery ───────────────────────────────────────────────────────

def _write_pool(d: Path, stem: str, n: int) -> None:
    for i in range(n):
        name = f"{stem}.ulaw" if i == 0 else f"{stem}_{i + 1}.ulaw"
        # Distinct contents so a test can tell the variants apart by bytes.
        (d / name).write_bytes(bytes([i + 1]) * 100)


def test_a_missing_first_clip_is_an_empty_pool(tmp_path):
    """The guard reads [] as 'no clip' and disables itself — the pre-existing
    behaviour for a branch whose audio_clips/ was never generated."""
    assert discover_clip_pool(tmp_path / "filler_checking.ulaw") == []


def test_a_lone_clip_is_a_pool_of_one(tmp_path):
    """Every deployed branch is in this state until the variants are cut. It
    must keep playing its single clip, not fall back to silence."""
    _write_pool(tmp_path, "filler_checking", 1)
    assert discover_clip_pool(tmp_path / "filler_checking.ulaw") == [
        tmp_path / "filler_checking.ulaw"
    ]


def test_the_pool_is_ascending_and_contiguous(tmp_path):
    _write_pool(tmp_path, "filler_checking", 4)
    pool = discover_clip_pool(tmp_path / "filler_checking.ulaw")
    assert [p.name for p in pool] == [
        "filler_checking.ulaw",
        "filler_checking_2.ulaw",
        "filler_checking_3.ulaw",
        "filler_checking_4.ulaw",
    ]


def test_discovery_stops_at_the_first_gap(tmp_path):
    """A regeneration that died after variant 2 leaves _4 on disk with no _3.
    Taking _4 anyway would play clips in an order nothing declared; a glob
    would do exactly that."""
    _write_pool(tmp_path, "filler_checking", 2)
    (tmp_path / "filler_checking_4.ulaw").write_bytes(b"\x09" * 100)
    pool = discover_clip_pool(tmp_path / "filler_checking.ulaw")
    assert [p.name for p in pool] == ["filler_checking.ulaw", "filler_checking_2.ulaw"]


def test_an_unrelated_file_in_the_directory_is_never_played(tmp_path):
    """The reason discovery is by name and not by glob. `filler_checking_old`
    is a plausible thing to leave lying about; it is not a thing to say to a
    patient."""
    _write_pool(tmp_path, "filler_checking", 2)
    (tmp_path / "filler_checking_old.ulaw").write_bytes(b"\x09" * 100)
    pool = discover_clip_pool(tmp_path / "filler_checking.ulaw")
    assert (tmp_path / "filler_checking_old.ulaw") not in pool


# ── 2. The rotation rule ────────────────────────────────────────────────────

def test_a_single_clip_pool_always_returns_the_only_index():
    assert next_clip_index(1, None) == 0
    assert next_clip_index(1, 0) == 0


@pytest.mark.parametrize("size", [2, 3, 5, 8])
@pytest.mark.parametrize("last", [0, 1])
def test_the_index_is_in_range_and_never_repeats_the_last(size, last):
    for _ in range(200):
        i = next_clip_index(size, last)
        assert 0 <= i < size
        assert i != last, "back-to-back is the only repeat a caller registers"


def test_every_variant_is_reachable():
    """A no-repeat rule implemented as 'always advance by one' would also pass
    the test above while making the pool a fixed carousel — predictable in a
    different way. Over enough draws each variant must come up."""
    seen = {next_clip_index(4, 0) for _ in range(500)}
    assert seen == {1, 2, 3}


# ── 3. The guard end to end ─────────────────────────────────────────────────

async def _armed_send(guard: FillerGuard, session: dict, sent: list) -> None:
    await guard.arm(session, delay_ms=10)
    await asyncio.sleep(0.05)
    guard.cancel()


async def test_consecutive_turns_do_not_play_the_same_recording(tmp_path):
    """The defect itself, at the level the caller experiences it."""
    _write_pool(tmp_path, "filler_checking", 4)
    sent: list[bytes] = []

    async def _send(b: bytes) -> None:
        sent.append(b)

    guard = FillerGuard(
        clip_path=tmp_path / "filler_checking.ulaw",
        send_audio=_send,
    )

    for _ in range(12):
        session = {"booking_flow_active": True}
        await _armed_send(guard, session, sent)

    assert len(sent) == 12, "every armed turn should have spoken once"
    for a, b in zip(sent, sent[1:]):
        assert a != b, "the same recording played on two consecutive turns"
    assert len(set(sent)) > 1, "the pool never rotated at all"


async def test_a_turn_that_never_spoke_does_not_advance_the_rotation(tmp_path):
    """A turn whose LLM answers inside the 350ms delay is cancelled having said
    nothing. If that turn consumed a variant, the next turn could legitimately
    play the one the caller last actually heard — the no-repeat rule has to
    track what was HEARD, not what was drawn."""
    _write_pool(tmp_path, "filler_checking", 2)
    sent: list[bytes] = []

    async def _send(b: bytes) -> None:
        sent.append(b)

    guard = FillerGuard(clip_path=tmp_path / "filler_checking.ulaw", send_audio=_send)

    # Turn 1 speaks.
    await _armed_send(guard, {"booking_flow_active": True}, sent)
    assert len(sent) == 1
    heard = sent[0]

    # Turns 2..6 are cancelled before the clip fires.
    for _ in range(5):
        await guard.arm({"booking_flow_active": True}, delay_ms=10_000)
        guard.cancel()
    assert len(sent) == 1, "a cancelled turn must not have spoken"

    # Turn 7 speaks — and must not repeat what was actually heard.
    await _armed_send(guard, {"booking_flow_active": True}, sent)
    assert len(sent) == 2
    assert sent[1] != heard


async def test_only_one_clip_is_ever_sent_in_a_turn(tmp_path):
    """The 2.5s second clip is gone (2026-08-29).

    It was the one hold producer that never called `decide_hold`, so the
    arbiter's "one head per turn" was a slogan rather than a property. This
    test replaces `test_the_second_clip_is_not_the_first_clip_repeated`, which
    asserted the two clips differed -- a property of behaviour that no longer
    exists. Waiting well past the old 2.5s escalation must still yield one clip.
    """
    _write_pool(tmp_path, "filler_checking", 3)
    sent: list[bytes] = []

    async def _send(b: bytes) -> None:
        sent.append(b)

    guard = FillerGuard(clip_path=tmp_path / "filler_checking.ulaw", send_audio=_send)
    await guard.arm({"booking_flow_active": True}, delay_ms=10)
    await asyncio.sleep(0.20)
    guard.cancel()

    assert len(sent) == 1, f"exactly one clip per turn, got {len(sent)}"


async def test_a_pool_of_one_still_speaks(tmp_path):
    """The state every branch is in before the variants are generated. Losing
    the filler here would reopen the 3-6s of dead air O-4 closed."""
    _write_pool(tmp_path, "filler_checking", 1)
    sent: list[bytes] = []

    async def _send(b: bytes) -> None:
        sent.append(b)

    guard = FillerGuard(clip_path=tmp_path / "filler_checking.ulaw", send_audio=_send)
    for _ in range(3):
        await _armed_send(guard, {"booking_flow_active": True}, sent)

    assert len(sent) == 3
    assert len(set(sent)) == 1


# ── 4. The declared pools ───────────────────────────────────────────────────

def test_no_two_clips_say_the_same_thing():
    """Two identical strings in the pool would spend an API call and a file to
    add nothing, and would let the "different variant" rule play the same
    sentence back to back."""
    import importlib.util

    root = Path(__file__).resolve().parents[2]
    spec = importlib.util.spec_from_file_location(
        "synthesise_filler", root / "scripts" / "synthesise_filler.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    texts = [t for t, _ in mod.CLIPS]
    assert len(texts) == len(set(texts)), "duplicate clip text"

    paths = [p for _, p in mod.CLIPS]
    assert len(paths) == len(set(paths)), "two clips writing to one file"


def test_the_declared_filenames_are_what_the_guard_discovers(tmp_path):
    """The script names the files and the guard finds them by name. Nothing
    connects the two but this convention, and a mismatch is invisible — the
    guard just quietly has a smaller pool."""
    import importlib.util

    root = Path(__file__).resolve().parents[2]
    spec = importlib.util.spec_from_file_location(
        "synthesise_filler", root / "scripts" / "synthesise_filler.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    for _, declared in mod.CLIPS:
        (tmp_path / declared.name).write_bytes(b"\x01" * 100)

    for stem in ("filler_checking", "filler_moment"):
        declared = [p.name for _, p in mod.CLIPS if p.name.startswith(stem)]
        found = [p.name for p in discover_clip_pool(tmp_path / f"{stem}.ulaw")]
        assert found == declared, (
            f"the {stem} pool declares {declared} but the guard discovers "
            f"{found} — the numbering conventions have drifted apart"
        )
